//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberAssistTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberAssistTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;ArrayOfSettingGroup&gt;&lt;SettingGroup&gt;&lt;TextureGroups&gt;&lt;TextureGroup&gt;&lt;Name&gt;world&lt;/Name&gt;&lt;MinLodSize&gt;256&lt;/MinLodSize&gt;&lt;MaxLodSize&gt;512&lt;/MaxLodSize&gt;&lt;LodBias&gt;1&lt;/LodBias&gt;&lt;MinMagFilter&gt;aniso&lt;/MinMagFilter&gt;&lt;MipFilter&gt;point&lt;/MipFilter&gt;&lt;NumStreamedMips&gt;0&lt;/NumStreamedMips&gt;&lt;MipGenSettings&gt;tmgs_simpleaverage&lt;/MipGenSettings&gt;&lt;/TextureGroup&gt;&lt;TextureGroup&gt;&lt;Name&gt;worldnormalmap&lt;/Name&gt;&lt;MinLodSize&gt;512&lt;/MinLodSize&gt;&lt;MaxLodSize&gt;1024&lt;/MaxLodSize&gt;&lt;LodBias&gt;1&lt;/LodBias&gt;&lt;MinMagFilter&gt;aniso&lt;/MinMagFilter&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string texture_groups {
            get {
                return ResourceManager.GetString("texture_groups", resourceCulture);
            }
        }
    }
}
